name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  pre-commit:
    uses: ./.github/workflows/reflow-pre-commit.yml

  python:
    uses: ./.github/workflows/reflow-python.yml

  validate:
    uses: ./.github/workflows/validate.yml

  checks:
    name: all
    if: ${{ !cancelled() }}
    needs: [pre-commit, python, validate]
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether all checks passed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  publish:
    name: Publish
    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'dev') }}
    needs: [checks]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "${{ github.ref_name }}" --title "${{ github.ref_name }}" --generate-notes
